[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "openjdk11"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile",
  "pnpm add --filter @splice/openapi @stoplight/prism-cli @openapitools/openapi-generator-cli"
]

[phases.build]
cmds = [
  "pnpm rebuild",
  "pnpm build"
]

[start]
cmd = "cd apps/web && pnpm start"
