[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "openjdk11"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm rebuild",
  "pnpm build"
]

[start]
cmd = "cd apps/web && pnpm start"
